.TH CHANGECASE 1
.SH NAME
changecase \- filter for changing case of input
.SH SYNOPSIS
.B changecase
.br
.SH DESCRIPTION
.I  changecase
is a filter which changes the case of the input according to the
configuration setting.
.PP
.I changecase
looks in the file
.I /etc/changecase.conf
to determine if it needs to uppercase or lowercase input.
.SH FILES
.DT
/etc/changecase		Configuration file
